### PR TITLE
Ensure the browser is closed

### PR DESCRIPTION
**Pull request by A5308Y**
even on a successful request. It seems `browser.close` wasn't reached somehow.

### CODE REVIEW

**Comment by A5308Y** [comment]
Now I finally understand: `browser.close` was executed before the pdf generation finished. With `await` it was a crash, because we "forced execution" (Is that how you say used `await`?) of `browser.close()`, before `page.pdf()` was executed at all. If I only remove the `await` in the original version the program doesn't crash, but at least the error is caught.

In that case we still get the "printing failed" error. I assume it's because we have to wait for the pdf generation to be finished before we can close the browser.

**Comment by A5308Y** [comment]
I tried around a lot, but I couldn't get a test to work. I thought it should be possible by using the call order, but
```js
it("generates the pdf before closing the browser", async () => {
  await app.inject({
    method: "POST",
    url: "/pdf",
    payload: {
      url: "https://google.com",
    },
  });
  const pdfOrder = pdf.mock.invocationCallOrder[0];
  const closeOrder = close.mock.invocationCallOrder[0];

  expect(pdfOrder).toBeLessThan(closeOrder)
});
```
but that also passes before this PR. I tried around a lot to get it to work, but I got lost a lot trying to figure out how promises can depend on each other and if that's really the problem. Maybe playwright checks during `page.pdf` if it has an open browser? I think someone with more JS experience could speed this up a lot. @rmehner @malfynnction

**Comment by rmehner** [comment]
> With await it was a crash, because we "forced execution" (Is that how you say used await?)

This is not how await works. In somewhat easy terms: `await` makes code sequential.

```js
const wait = (duration) =>
  new Promise((resolve) => setTimeout(resolve, duration));

const withoutAwait = () => {
  console.log(`${Date.now()} mainWithoutAwait: before wait`);
  wait(5000); // <-- execution of the function will continue without pause
  console.log(`${Date.now()} mainWithoutAwait: after wait`);
};

const withAwait = async () => {
  console.log(`${Date.now()} mainWithAwait: before wait`);
  await wait(5000); // <-- execution of the function will wait here until the promise resolves
  console.log(`${Date.now()} mainWithAwait: after wait`);
};

withoutAwait();
withAwait();
```

(https://jsbin.com/xoyovinosu/edit?js,console for easy consumption)

If you run this, you'll see that the log output on the second function call will appear around 5s later after the first log. For the first function you'll not see any pause.

This is what `await` is all about. It makes it easier to wait for things if you rely on the execution order (e.g. you need a database result coming back before you continue)

What I've said is that we likely don't need to await the `browser.close` call, as we don't care too much about the browser being closed after the execution.

What I'm wondering is: How can I reproduce the error and what was the error message?

**Comment by A5308Y** [comment]
We have a solution now BTW. Thanks for the explanation. I'll look at it soon.

**Comment by rmehner** [comment]
Also the thing about nested finally -> https://jsbin.com/ganihimeba/edit?js,console ... also works as expected.

**Comment by A5308Y** [comment]
> What I'm wondering is: How can I reproduce the error and what was the error message?

I used postman with:

```
localhost:8000/pdf

{
  "url": "https://google.com",
  "pdfOptions": {}
}
```

to reproduce the error.

```
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

page.pdf: Protocol error (Page.printToPDF): Printing failed
    at createPDF (file:///Users/andy/repositories/code/Active/bits-to-dead-trees/app.js:57:19)
    at async Object.<anonymous> (file:///Users/andy/repositories/code/Active/bits-to-dead-trees/app.js:123:16) {
  name: 'Error'
}
```

I think I pasted this in slack before.

**Comment by A5308Y** [comment]
@malfynnction helped me with the test and we found this solution. We now think it was a race condition between `browser.close` and `page.pdf`.

**Review by malfynnction — APPROVED** [review]
I helped write the test so I'm not sure if I'm qualified to approve 🤔 But I think it looks good!

**Comment by A5308Y** [comment]
This is blocking https://www.pivotaltracker.com/story/show/184239207 and https://www.pivotaltracker.com/story/show/184154707 so it would be nice to have a new release soon. 

Do you have time to look at this today @rmehner?

**Comment by rmehner** [comment]
The problem indeed has been a race condition caused by us. We didn't await the result of the `pdf` call and therefore `browser.close` came to early. A broken release :(

We should add a smoke test that doesn't use any mocking and creates a real PDF from a page.

**Comment by A5308Y** [comment]
```
-      return page.pdf(pdfOptions);
+      return await page.pdf(pdfOptions);
```
> This will fix the issue at hand

Yes, for the success case, but it'll introduce another bug:

```
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```
When requesting a 404.

I started with this, but then it got more complicated.

**Comment by A5308Y** [comment]
> We should add a smoke test

Agreed, but can we do this after releasing this fix. I would need a very long time to set up a smoke test and would like to have some results for Lea.

**Comment by rmehner** [comment]
```diff
diff --git a/app.js b/app.js
index 843307e..874ce0f 100644
--- a/app.js
+++ b/app.js
@@ -54,10 +54,10 @@ const createPDF = async (
 
     const response = await page.goto(url, gotoOptions);
     if (response?.ok()) {
-      return page.pdf(pdfOptions);
+      return await page.pdf(pdfOptions);
     }
 
-    return Promise.reject({
+    return await Promise.reject({
       error: true,
       message: await response?.text(),
       status: response?.status(),
```

**Comment by A5308Y** [comment]
Ok. Didn't know that worked. Do you think that would be a better PR? 

I think having only one try-catch-finally block is easier to understand and the test adds value to.

**Comment by rmehner** [comment]
@A5308Y Can you squash some of those commits so it's easier to follow the history? Thanks

After that, it should be ready to merge and a new version can be published.

**Comment by A5308Y** [comment]
> Can you squash

Like this?

**Pull request merged**
